export const SYSTEM_ROUTES = {
    LOGIN_AUTH_SCREEN: {
        ROUTE: 'LOGIN_AUTH_SCREEN',
    },
    APP_BOTTOM_TAB_NAVIGATOR: {
        ROUTE: 'APP_BOTTOM_TAB_NAVIGATOR'
    },
    MORE_OPTIONS_STACK_NAVIGATOR: {
        ROUTE: 'MORE_OPTIONS_STACK_NAVIGATOR',
        BOTTOM_LABEL: 'Mais'
    },
    HELP_PET_STACK_NAVIGATOR: {
        ROUTE: 'HELP_PET_STACK_NAVIGATOR',
        BOTTOM_LABEL: 'Ajudar'
    },
    INFORM_PET_STACK_NAVIGATOR: {
        ROUTE: 'INFORM_PET_STACK_NAVIGATOR',
        BOTTOM_LABEL: 'Informar'
    },
    REGISTER_PET_SCREEN: {
        ROUTE: 'REGISTER_PET_SCREEN',
        HEADER_TITLE: 'Informar sobre um pet'
    },
    MORE_OPTIONS_SCREEN: {
        ROUTE: 'MORE_OPTIONS_SCREEN',
        HEADER_TITLE: 'Mais'
    },
    CHOOSE_HELP_SCREEN: {
        ROUTE: 'CHOOSE_HELP_SCREEN',
        HEADER_TITLE: 'Ajude um pet'
    },
    HELP_AND_DONATION_SCREEN: {
        ROUTE: 'HELP_AND_DONATION_SCREEN',
    },
    CUPONS_LIST_SCREEN: {
        ROUTE: 'CUPONS_LIST_SCREEN'
    },
    COMPATIBLE_PETS_SCREEN: {
        ROUTE: 'COMPATIBLE_PETS_SCREEN'
    },
    NEW_CUPOM_SCREEN: {
        ROUTE: 'NEW_CUPOM_SCREEN'
    },
    COMPATIBLE_PET_DETAILS: {
        ROUTE: 'COMPATIBLE_PET_DETAILS'
    },
    PET_SELECTED_HELP_SCREEN: {
        ROUTE: 'PET_SELECTED_HELP_SCREEN'
    },
    REGISTER_HELP_SCREEN: {
        ROUTE: 'REGISTER_HELP_SCREEN'
    },
    LOGIN_STACK_NAVIGATOR: {
        ROUTE: 'LOGIN_STACK_NAVIGATOR'
    },
    REGISTER_ACCOUNT_SCREEN: {
        ROUTE: 'REGISTER_ACCOUNT_SCREEN'
    },
    GATHER_INFORMATION_COMPATIBLE_SCREEN: {
        ROUTE: 'GATHER_INFORMATION_COMPATIBLE_SCREEN'
    },
}